---
- name: AWS - Find AMI Info
  hosts: localhost
  gather_facts: no

  vars:
    # Sydney is ap-southeast-2
    # North Virginia is us-east-1
    - target_ami_name: "RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2"
    - target_owners: "309956199498"

  tasks:
  - name: find current AMIs in this region
    ec2_ami_info:
      region: "{{ target_aws_region }}"
      owners: "{{ target_owners }}"
      filters:
        name: "{{ target_ami_name }}"
    register: found_amis

  # Show All AMIs found
  - debug:
      var: found_amis

  # We will use the latest found ami id, sorted by creation date
  - name:  set new instance ami id
    vars:
      new_instance_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
    debug:
      msg: "{{new_instance_ami.image_id}}"
...
