---
- name: AWS - Delete Instance
  hosts: localhost
  gather_facts: no

  vars:
    - target_instance_name: "aws-rhel-webserver-1"
    # Sydney is ap-southeast-2
    - target_aws_region: "ap-southeast-2"

  tasks:
  - name: find instance id
    ec2_instance_facts:
      region: "{{ target_aws_region }}"    
      filters:
        "tag:Name": "{{ target_instance_name }}"
    register: found_instance
  
  - debug:
      msg: "{{ found_instance.instances[0].instance_id }}"

  - name: delete instance
    ec2:
      instance_ids: [ "{{ found_instance.instances[0].instance_id }}" ]
      region: "{{ target_aws_region }}"
      state: absent
...