---
- name: AWS - Create RHEL Server AMI
  hosts: localhost
  gather_facts: no

  vars:
    - target_instance_name: "aws-rhel-webserver-1"
    # Sydney is ap-southeast-2
    # North Virginia is us-east-1
    - target_aws_region: "ap-southeast-2"
    - target_ami_name: "RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2"
    - target_owners: "309956199498"
    - target_instance_type: "t2.micro"
    - target_key_name: "aws-ssh-key-1"
    - target_vpc_subnet_id: "subnet-dc7130ab"
    - target_volume_size: "15"
    # Security Group Options: ssh-http, ssh-mysql, winrm-rdp-http
    - target_security_group: "ssh-http"    
    # Tags
    - target_tag_ansible_group: "syd_aws_linux"
    - target_tag_demo_type: "syd_3tier_webserver_linux"

  tasks:
  - name: find current RHEL AMI in this region
    ec2_ami_info:
      region: "{{ target_aws_region }}"
      owners: "{{ target_owners }}"
      filters:
        name: "{{ target_ami_name }}"
    register: found_amis

  # Show All AMIs found
  #- debug:
  #    var: found_amis

  # We will use the latest found ami id, sorted by creation date
  - name:  set new instance ami
    vars:
      new_instance_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
    debug:
      msg: "{{ new_instance_ami.image_id }}"
  
  - name: launch new AMI instance
    vars:
      new_instance_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"  
    ec2:
      region: "{{ target_aws_region }}"
      image: "{{ new_instance_ami.image_id }}"
      instance_type: "{{ target_instance_type }}"
      group: "{{ target_security_group }}"
      key_name: "{{ target_key_name }}"
      vpc_subnet_id: "{{ target_vpc_subnet_id }}"
      state: present
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: "{{ target_volume_size }}"
          delete_on_termination: true
      instance_tags:
        Name: "{{ target_instance_name }}"
        ansible_group: "{{ target_tag_ansible_group }}"
        demo_type: "{{ target_tag_demo_type }}"
      assign_public_ip: yes 
      wait: yes
      wait_timeout: 500
      count: 1
    register: new_ec2

  # Show New Instance
  - debug:
      var: new_ec2

  - name: wait until ssh is ready
    wait_for:
      delay: 30
      timeout: 600
      port: 22
      host: "{{ new_ec2.instances[0].dns_name }}"
...